### ISSUE TITLE
manifest parse error(s): 1 swift package

### ISSUE THREAD

**Issue by shleykin** [exercism/support#11]
Hello !

I am trying to configure Xcode and running tests(swift) ,error occurs at this stage:

_execute swift package generate-xcodeproj_

Error:

l3mac:hello-world l3$ swift package generate-xcodeproj
/Users/l3/Exercism/swift/hello-world: error: manifest parse error(s):
1
I tried to find a solution, so far without success, maybe you will help, thanks in advance!

Xcode Version 10.1 (10B61)
mojave 10.14.3

swift tests
swift builds

same error

exercism version 3.0.11
Your system is ready to brew.

**Comment by iHiD** [comment]
Can this be closed?

**Comment by shleykin** [comment]
Yes
