### ISSUE TITLE
Not getting Object name in src/main/scala folder

### ISSUE THREAD

**Issue by ithakur1** [exercism/support#12]
Hello All,

I am not getting in scala file in the folder src/main/scala. 
I just get a .keep file.

Although I get a Test file in the test folder which has the object name in it.
But I got the object name in main folder as well for hello-world and sum of multiples examples. But after that I am not getting it. Could you suggest a bit on that?

**Comment by iHiD** [comment]
Can this be closed?

**Comment by ithakur1** [comment]
yes
