### ISSUE TITLE
Problems with installing gem minitest 

### ISSUE THREAD

**Issue by ShreeMsethi** [exercism/support#15]
Unable to install the gem minitest. Downloading the test also gets effected because of this issue. Any help would be much appreciated. Thanks 

<img width="754" alt="Screen Shot 2019-05-11 at 2 56 28 AM" src="https://user-images.githubusercontent.com/37888890/57566277-985d8600-7398-11e9-8bd2-d41d49b442c7.png">

**Comment by sshine** [comment]
I'm closing this issue, as @ShreeMsethi hasn't responded.
