### ISSUE TITLE
Stuck waiting for mentors in Rust track

### ISSUE THREAD

**Issue by alejandromarcu** [exercism/support#17]
Hi,
I'm in the Rustr track and loving it!  At first the mentors were replying pretty quickly, often in a few hours.  But now I haven't heard any responses in almost 2 weeks (I re-submitted just adding a blank line in case it triggers something).  I also did all the side exercises that were available to me.
I'd love to have mentor feedback and keep going, but otherwise I'd be happy if I can continue in parallel doing more side exercises or start with the next core exercise.  Otherwise I can switch to independent mode, but I think the feedback provided from mentors is very useful and makes a difference in just making it work vs doing it the best Rust allows for.
Thanks!

**Comment by sshine** [comment]
Hi @alejandromarcu and @medmond78. Yes, this is very much a problem on some tracks. Unfortunately there's not much we can do about it in the short run, but Exercism has several projects going aimed at reducing the waiting time for mentoring feedback. I hope you've found a way to enjoy mentored mode or have made the switch to independent mode.
