### ISSUE TITLE
Finished exercise and unable to move onto the next one

### ISSUE THREAD

**Issue by samnooby** [exercism/support#2]
I finished the second exercise for the go track (two-fer). The code works fine and I was able to submit it to exercism and see my code online but on the main track page it still says in progress and doesnt let me look at the next track.

My exercism troubleshoot:
Version
----------------
Current: 3.0.11
Latest:  3.0.11

Operating System
----------------
OS:           linux
Architecture: amd64

Configuration
----------------
Home:      /home/sam
Workspace: /home/sam/exercism
Config:    /home/sam/.config/exercism
API key:   [Insert key here]

API Reachability
----------------
GitHub:
    * https://api.github.com
    * [connected]
    * 103.732795ms
Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 495.016083ms

**Comment by sshine** [comment]
@samnooby: I'm assuming you have progressed since this issue was reported, so I'm closing this issue. Let us know if you're unable to progress for another reason than waiting for mentoring, and let us know if this cause is not clearly enough indicated after having submitted.
