### ISSUE TITLE
Not Able To Upload

### ISSUE THREAD

**Issue by gambledrum** [exercism/support#3]
I'm using the following command prompt and I'm getting an error.  I'm using Windows 10 and the version of Exercism is exercism version 3.0.11.  I don't know what metadata means in the error message and the site I'm directed to doesn't seem to help me.

exercism submit hello-world.lisp
Error:

    The exercise you are submitting doesn't have the necessary metadata.
    Please see https://exercism.io/cli-v1-to-v2 for instructions on how to fix it.

**Comment by sshine** [comment]
@gambledrum: Have you been able to progress? I am closing this issue because of time having passed, but post a comment here if this is not the case, and we can resume debugging.

**Comment by gambledrum** [comment]
I'm good.  Thanks.

    On Sunday, September 29, 2019, 12:23:41 PM EDT, Simon Shine <notifications@github.com> wrote:  
 
 
@gambledrum: Have you been able to progress? I am closing this issue because of time having passed, but post a comment here if this is not the case, and we can resume debugging.
