### ISSUE TITLE
Submit error: Not in the workspace

### ISSUE THREAD

**Issue by mikoSL** [exercism/support#36]
I am totally new to exercism and tried to submit the helloword in scala-track

I configured exercism according to the instructions.

When I tried to submit, I have some problems:

I use Mac and I am in the directory:

```sh
$pwd  
show **/Users/myname/exercism/scala/hello-world**
```

In this directory, I tried 
`exercism submit /Users/myname/exercism/scala/hello-world/src/main/scala/HelloWorld.scala`
It showed `Error: not in workspace"

I tried 
`exercism submit HelloWorld.scala`
It showed `Error, file not found`

Any suggestion? I am really stuck! 
Thank you for your time.

**Comment by wbnns** [comment]
If you're setting a custom workspace, try putting quotations around the path. That fixed it for me.

**Comment by kotp** [comment]
Thank you @wbnns.

**Comment by kopalsoni** [comment]
I tried all the solutions above, none of them worked :( 
I'm using windows

**Comment by NobbZ** [comment]
Can you please provide a little bit more info?

Like your `exercism version`, the command you use to try to submit, the working dir that is active at that moment, the exact error message you see?

**Comment by sawaveys** [comment]
I'm having the same issue and none of the above solutions are working for me. Tried capitalising the E. Heres the message it displays

MacBook hello-world % pwd
/Users/myName/Exercism/javascript/hello-world
MacBook hello-world % exercism submit hello-world.js
Error: lstat /Users/myName/exercism/javascript/hello-world/YOUR_PATH: no such file or directory

**Comment by wbnns** [comment]
@sawaveys 

Hi, try: `exercism configure - w '/Users/myName/Exercism'`

Then try to submit again. I'm assuming maybe `myName` will need to be replaced by your system username.

**Comment by sawaveys** [comment]
@wbnns Thank you ! That worked for me

**Comment by lokiandfengshui** [comment]
> @sawaveys
> 
> Hi, try: `exercism configure -w '/Users/myName/Exercism'`
> 
> Then try to submit again. I'm assuming maybe `myName` will need to be replaced by your system username.

Saved my day. Thanks!

**Comment by lokiandfengshui** [comment]
> @wbnns
> 
> Hi, try: `exercism configure -w '/Users/myName/Exercism'`
> 
> Then try to submit again. I'm assuming maybe `myName` will need to be replaced by your system username.

Saved my day. Thanks!

**Comment by SichangHe** [comment]
This happened to me just now on macOS
## behavior
```shell
$ exercism submit sth
Error: not in workspace
$ exercism workspace
/Users/username/Exercism
```

## solution
```shell
exercism configure -w '~/exercism'
```

**Comment by kotp** [comment]
@SichangHe the "solution" does not solve the shown problem in the "behavior" portion.

The `sth` is likely wrong, as there is no extension.  It should be `exercism submit hamming.scala`, for example, so it will be common and expected that this is not going to be found in the workspace.

The solution does not solve the shown problem.

**Comment by SichangHe** [comment]
@kotp Please assume there is an extension in the `sth`, otherwise you would miss the point.

Anyway, I found macOS wonky. The file path on the system changed from `~/exercism` to `~/Exercism` automatically and changed back. No idea how it happened.

**Comment by kotp** [comment]
Please do not make us assume things in a technical support forum.  It means that we will also assume that typographical errors do not exist, wrong commands are not really wrong.  Instead, show what you have done accurately, and then we can help more easily because we will have accurate information to work from.

(It sounds perhaps a little bit mean, but intended instead to be kind.  If you give accurate and real information (aside from where we should obfuscate things like passwords and security key information) then we can accurately help you.)

If it is any consolation, I find MacOS wonky as well.  Glad that you have found the solution.
