### ISSUE TITLE
Cannot delete team

### ISSUE THREAD

**Issue by Szasza** [exercism/support#43]
Hi Exercism Team,

Could you please let me know how a team I created can be deleted? I have found no way of doing so.

Thank you for your help.

**Comment by NobbZ** [comment]
Hi @Szasza!

Currently it is not possible to delete a team. Please tell us the name of your team here and your username within that team.

@iHiD will then take care of the issue.

**Comment by Szasza** [comment]
Hi @NobbZ,

Thank you for the quick response.

The team URL is https://teams.exercism.io/teams/klorf-abaf12bc and I am the only user in it.

Thank you and @iHiD for the help, it is much appreciated.

**Comment by Szasza** [comment]
Hi @NobbZ and @iHiD ,

I hope all is well.

During 'spring' cleanimg I have noticed that this issue is still open.

Could you please verify that the deletion has been taken care of?

Thank you for your help.

**Comment by NobbZ** [comment]
@iHiD is in a 2 week long digi-detox, not sure if he will be able to take care of this before midst of September.

@ErikSchierboom have you necessary access or do you know someone who does.

**Comment by Szasza** [comment]
@NobbZ thank you for your response.

Unfortunately since this wasn't just an administrative notification miss but the deletion actually wasn't done, I have sent an email to privacy@exercism.io to request a complete data deletion as per GDPR which has set deadlines from now on.

I am closing this issue to avoid double-up communication, thank you again for your assistance in resolving the data deletion request as soon as possible.

@iHiD @ErikSchierboom FYI.

**Comment by ErikSchierboom** [comment]
@NobbZ I don't have access nor do I know anyone that does. @Szasza would you be okay with the data being removed once @iHiD is back (which is in two weeks)?

**Comment by Szasza** [comment]
Hi @ErikSchierboom ,

Thank you for your response, it is much appreciated.

The issue is already taken care of, no further action is needed.

Thank you again.

**Comment by ErikSchierboom** [comment]
Brilliant! Thanks.
