### ISSUE TITLE
Track progress not updating

### ISSUE THREAD

**Issue by tuyenhn** [exercism/support#46]
Hi, I'm very new to Exercism and don't know how things work. I followed the interactive CLI installation walkthrough and installed Exercism. I use VSCodium as my personal IDE with MinGW64.

I tested the first "hello world" exercise and submitted it but when I went to the solution page (https://exercism.io/my/solutions/8566acf4c5544394bd910cf2bcf1a8f0), it said "Oh dear, we can't find that page. Sorry about that." and the hello world exercise is still incomplete.

I just need to "exercism submit ..." in the cmd right? or are there any extra steps?

---This is a copypasta from the original post since it's recommended that the issue is more suitable here. Link to the original post with steps taken by me: exercism/c#391

**Comment by NobbZ** [comment]
Yes, `exercism submit` should usually "just work".

Every now and then though, we encounter this bug.

Could you please do `exercism submit --verbose …` and post the full command you issued as well as the output here?

Please use proper code fences (or indent by 4 spaces) when you paste the code.

**Comment by tuyenhn** [comment]
What i entered into the cmd

    exercism submit C:\Users\Tuyen\Exercism\c\hello-world\src\hello_world.c C:\Users\Tuyen\Exercism\c\hello-world\src\hello_world.h

Then the cmd will throwback 


     Your solution has been submitted successfully. 
     You can complete the exercise and unlock the next core exercise at:

     https://exercism.io/my/solutions/8566acf4c5544394bd910cf2bcf1a8f0

**Comment by NobbZ** [comment]
And with the `--verbose` switch?

**Comment by tuyenhn** [comment]
Ah my bad, didn't know it was a switch.

With the `--verbose` switch:

```
========================= BEGIN DumpRequest =========================
PATCH /v1/solutions/8566acf4c5544394bd910cf2bcf1a8f0 HTTP/1.1
Host: api.exercism.io
Authorization: Bearer 8e8095a6-d692-4736-ab03-8cdf9d222827
Content-Type: multipart/form-data; boundary=4896a113f3894ee459e109f744f219cf0eac5092c1c50c9a46c6d3a01077
User-Agent: github.com/exercism/cli v3.0.11 (windows/amd64)

--4896a113f3894ee459e109f744f219cf0eac5092c1c50c9a46c6d3a01077
Content-Disposition: form-data; name="files[]"; filename="src/hello_world.c"
Content-Type: application/octet-stream

#include "hello_world.h"

const char *hello(void){
    return "Hello, World!";
}

--4896a113f3894ee459e109f744f219cf0eac5092c1c50c9a46c6d3a01077
Content-Disposition: form-data; name="files[]"; filename="src/hello_world.h"
Content-Type: application/octet-stream

#ifndef HELLO_WORLD_H
#define HELLO_WORLD_H

const char *hello(void);

#endif

--4896a113f3894ee459e109f744f219cf0eac5092c1c50c9a46c6d3a01077--

========================= END DumpRequest =========================


========================= BEGIN DumpResponse =========================
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Sat, 06 Jul 2019 04:47:19 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx/1.10.3 (Ubuntu)
Set-Cookie: _exercism_session=zsvm7vOcje7BVz3he7nYKzfw5HAXC2z%2BxPn1Edf1SFp8zEFJDvgFfOnDQuxodrJJcni8V3Lslx4LqGDpvNPw9DaO2JsZD0rWKMwKxBI54g4wt2x0f2tmZdi9OJpp3H%2F8tufxPnG3RWVyOZ9%2Beqotb7mBoA%3D%3D--DMvU19f7JX%2F1g3Af--WJmuZmpJ%2Fgw2lKjnVfZaNg%3D%3D; domain=.exercism.io; path=/; HttpOnly
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: f5df0556-4e6e-404f-bd3a-9a85c1d5523d
X-Runtime: 0.142164
X-Xss-Protection: 1; mode=block


========================= END DumpResponse =========================



    Your solution has been submitted successfully.
    You can complete the exercise and unlock the next core exercise at:

    https://exercism.io/my/solutions/8566acf4c5544394bd910cf2bcf1a8f0
```

**Comment by NobbZ** [comment]
Reporting success is a known bug that has been fixed in the CLI already, but no new release has been bundled since then. (exercism/cli#790)

Why though the submit fails at all has to be checked by the people with database access. I have pinged one of them privately in chat.

**Comment by tuyenhn** [comment]
Ah i see, thanks a lot!

**Comment by iHiD** [comment]
Hello. @NobbZ pinged me to check the db.

So that solution id no longer exists in the database. Which is very strange. Did you maybe leave and rejoin the track? The correct solution id is `eaece793fb6940e8aa974a03102025da`. If you edit the `.solution.json` file and change the id to that, that should then submit. 

I'll leave @Nobbz to help you from here :)

**Comment by NobbZ** [comment]
The actual file to change is `.exercism/metadata.json`.

It's a JSON file and you need to edit the `"id"`.

**Comment by tuyenhn** [comment]
Oh hey, it works! Thanks a lot, guys!

I might have left and rejoined the track before cause I think that would solve the problem, it's all a blur tbh.

Anyway thanks a lot!
