### ISSUE TITLE
Totally lost

### ISSUE THREAD

**Issue by VitruviusX** [exercism/support#49]
So I was trying to use Exercism/CLI? and I already have python 3.7 installed. I manually install Exercism to windows fine.  In order to run the tests it says to install pytest but to install pytest I need pip. But I think that python 3.7 already has pip. But I still need to install pytest. Somehow I ended up in the command line for my computer. command line didn't recognize python or pip. It didn't recognize python I think because the PATH and environmental and local variables were wrong? But I can only change the PATH temporarily through the command line and I need access to the system settings to change PATH to include python so that I can use command line to install pytest so I can use Exercism/CLI? Nothing I typed into command line was recognized except one thing I copied and pasted about setx and python37 added something to the directory, I cant look at it again because it said to reboot command line to have it do something, python still wasn't recognized in there. 

This seems awfully confusing/complicated to do the first exercise which is Hello_World! on the python path. I don't know much about computers so this is a tough line to start on. 

tldr; installed exercism/CLI, cant get pytest, command line wont recognize python, PATH, environmental variables, setx did something. 

Zac

**Comment by NobbZ** [comment]
@VitruviusX have you been able to sort this out or do you still have problems?

**Comment by VitruviusX** [comment]
> @VitruviusX have you been able to sort this out or do you still have problems?

Hello, Thank you for your response. So I typed exercism version into my command prompt and got 3.0.12. So I assume this means I have exercism. 

From here how do I get to submitting the first "Hello World" assignment. I assume I have pip-3 since I have the most up to date python. Do I need pytest then to run the tests? 

Also silly question, when I try to open IDLE it just opens a python shell that doesn't allow me to edit the code just type one liners and hit enter. 

TLDR; have exercism and pip, how to get to submitting first hello world? how do I open the python editor instead of the shell when I click IDLE?

Does this all make sense? 

Thanks again!

-V

**Comment by NobbZ** [comment]
I have no clue what IDLE is. But in general you can use any editor you like, I prefer VScode and Emacs.

And yes, you should be able to run the tests by running `pytest` from the exercises folder. Perhaps you might need to specify the test file as well, I'm not exactly sure. But that should be explained in the README which I currently do not have access to easily as I'm on my mobile only.

**Comment by VitruviusX** [comment]
Thank you, 

When I go to "Running the Tests" page it says "Installing pytest..we recommend you install pytest and pytest-cache. pytest is a testing tool that will give you more flexibili........When I click pytest(hyperlink) it just brings up a page that says "Sorry This page does not exist yet." I feel like this is all way more complicated than it should be right?

Thanks, no worries about not being able to see stuff on mobile, I'm in no hurry. I appreciate the help.

**Comment by VitruviusX** [comment]
> I have no clue what IDLE is. But in general you can use any editor you like, I prefer VScode and Emacs.
> 
> And yes, you should be able to run the tests by running `pytest` from the exercises folder. Perhaps you might need to specify the test file as well, I'm not exactly sure. But that should be explained in the README which I currently do not have access to easily as I'm on my mobile only.

Thank you,

When I go to "Running the Tests" page it says "Installing pytest..we recommend you install pytest and pytest-cache. pytest is a testing tool that will give you more flexibili........When I click pytest(hyperlink) it just brings up a page that says "Sorry This page does not exist yet." I feel like this is all way more complicated than it should be right?

Thanks, no worries about not being able to see stuff on mobile, I'm in no hurry. I appreciate the help.

**Comment by NobbZ** [comment]
Well, that broken link is an issue we need to tell @exercism/python about, I hope mentioning them here is enough to draw attention.

Installation though is described just one sentence later:

> If you want to install pytest for Python 2, then use pip.
>
> pip install pytest pytest-cache
> If you instead want the version of pytest for Python 3, then use pip3.
>
> pip3 install pytest pytest-cache

Even though that mentions the use of `pip3`, depending on your installation method of python it might be just `pip` nowadays.

**Comment by VitruviusX** [comment]
> Well, that broken link is an issue we need to tell @exercism/python about, I hope mentioning them here is enough to draw attention.
> 
> Installation though is described just one sentence later:
> 
> > If you want to install pytest for Python 2, then use pip.
> > pip install pytest pytest-cache
> > If you instead want the version of pytest for Python 3, then use pip3.
> > pip3 install pytest pytest-cache
> 
> Even though that mentions the use of `pip3`, depending on your installation method of python it might be just `pip` nowadays.

Okay, it seems to say that if you downloaded python 3 recently off the python website that pip3 is already installed I think. All that left is getting the pytest however the section you highlighted "pip install pytest pytest-cache" has pytest and pytest-cache as red letters but they are not links, are they links for you? Is that where you go to get access to pytest and pytest-cache? If the pytest link at the top of the screen is the only way then yeah its currently out of order, a maze shows up and says the page doesn't exist anymore. 

tldr; are pytest and pytest cache links I cant access? Is the pytest link at top of screen that "does not exist yet" the only way to get pytest?

Thanks again for all of your help!

**Comment by cmccandless** [comment]
`pip install pytest pytest-cache` is the command you run in your terminal to install `pytest` and `pytest-cache`.

The broken link is due to https://pytest.org/latest moving to https://pytest.org/en/latest, and I am addressing that change now.

**Comment by cmccandless** [comment]
The broken link has been fixed in exercism/python#1901.

`pip install pytest pytest-cache` is a terminal command to install `pytest` and `pytest-cache`.

**Comment by VitruviusX** [comment]
The link works! I will forge on and try to install pytest! Thank you both so much.

**Comment by VitruviusX** [comment]
Hello, 

So I went to install pytest but apparently I didn't have pip afterall because my CMDprompt doesn't recognize it . I went to install pip but it didn't let me so I tried setting my path of pip to the path system variable with setx PATH "%PATH%;C:\Python34\Scripts" .. it said "SUCCESS: Specified value was saved. 

from there I tried(in commandprompt):  c:\python27\scripts\pip.exe install [pytest].whl (system cannot find the path specified) ...pip install -U pytest(pip is not recognized as internal or external command) ..$ pytest --version($ is not recognized as int.......)  .. pip3 install pytest(pip3 is not recognized as an interna.....) 

Nightmare haha

**Comment by cmccandless** [comment]
Using Python in windows requires a few extra steps... I recommend using the Git Bash terminal (should have installed with Git).

Aside from that, if you can run python.exe, try
```
$ python -m pip install -U pytest
```

**Comment by VitruviusX** [comment]
I installed git bash. It comes as a small black square I can type prompts into. typing python -m pip install -U pip leads to "command not found." same if I type any combination of those words.

**Comment by yawpitch** [comment]
@VitruviusX can you explain, precisely, what version of Windows you are using and what steps you used to install Python 3.7? There are several different ways to install Python on Windows, but ideally you’ve used the full installer as mentioned [here](https://docs.python.org/3/using/windows.html#the-full-installer), which _should_ have installed both Python and pip, but you may not have checked the box to add the install directory to your PATH. Since you’re getting the command not found error it seems likely you did not. You may need to uninstall and then reinstall with that box selected to get your new Python install working.

I see above you manually trying to fix this, but you seem to be trying to set the PATH to point at a Python 3.4 installation when you said you’d install Python 3.7. Moreover you seem to be pointing at a system-wide install, rather than the user installation you should get by default.

**Comment by VitruviusX** [comment]
Thanks. I tried redownloading python with pip selected and environmental variables but I need administrative approval. considering I already had to have IT come up and approve downloading python the first time I think I'm just going to go without instead of making them make a second trip.. maybe if I get my own computer some time. Access to python and all of this stuff is way too inaccessible. Way too many hurdles that someone with less knowledge couldn't possibly get over. 

ps. pip was already selected when I tried installing python again just now so I'm assuming it was selected when I downloaded it the first time so I think pip has to be on my computer, I wouldn't have deselected it. 

Thanks everyone.

**Comment by NobbZ** [comment]
Why don't just ask the department to properly install python for you?

Or as I did at work, I let the department install virtual box a single time, and since then I maintain my own sandboxed Linux inside that VM, rarely using actual windows software.

After you managed to get through the first couple of hurdles Linux usually is much easier to develop on unless you target windows...

**Comment by VitruviusX** [comment]
Hey, 

That's a good idea. yea the department didn't really know what they were doing because they don't usually download this kind of stuff. I work in biochemistry and work at a hospital so they like to keep control of their computers. Next time they come up I might see if they'll redo python but I doubt they'll let me run wild and free in the computer just because there is legal stuff with hospital computers with healthcare type data. Although I have heard some people talking about needing to download a graphing package for work and they might need to set up a VM for that which I might be able to use as an in to getting all of my programming needs. 

craziness I know!

Thanks

**Comment by yawpitch** [comment]
@VitruviusX if you're using the Python 3.7 Full Installer I mentioned before then you _should not_ need administrator approval to install it to your local user account _and_ have it update the PATH correctly _unless_ your IT department has so completely locked down your user account that you couldn't possibly install it without their help anyway. You may have selected an "all user" install, which would require admin privileges, but IIRC that shouldn't be selected by default.

Your mentioning "re-downloading" has me a bit unsure about how you're installing though ... the Full Installer is an .exe file that you can run more than once to install, update, and uninstall, there should be no cause to download more than once, or to selected pip when downloading. The web installer should work the same way, it's just a smaller file that has to download some components locally.

**Comment by VitruviusX** [comment]
As in go to python.org and click download python 3.7.4? That's locked(its what IT downloaded the first time but requires IT every time you go into it) But what downloading it off the website the first time gave me is below: 

When I go to my start menu and click python3.7 there are 4 options: 1. IDLE(python 3.7 32-bit) 2. python 3.7(32-bit), 3. python 3.7 manuals (32-bit), 4. python 3.7 module docs(32.-bit)

**Comment by yawpitch** [comment]
Those menu items represent an installed copy of Python. That installed copy most likely came from an installer file, depending on which link you're talking about. If they temporarily allowed you to download it by signing in with admin access it's probably in your Downloads folder still. Double clicking that should allow you to update your installation, uninstall, and re-install. Uninstalling and re-installing with the "add to PATH" checkbox clicked _should_ get you a user installation with the PATH correctly set up for your account, meaning you should then be able to launch CMD.exe and type `where python` and hit Enter to know where it's installed.

**Comment by VitruviusX** [comment]
When I double click python in my downloads I come to an optional features box with checkbox options: 
1. documentation
2. pip
3. td/tk and IDLE
4. python test suite
5. py launcher
6. for all users

These are automatically all checked. I click next. 
advanced options: checked boxes: 
1. install for all users
2. associate files with python
3. create shortcuts for installed applications
4. add python to environment variables
5. precompile standard library
6. download debugging symbols
7. download debug binaries

"customize install location" is listed underneath the check boxes with a browse button. 

boxes 2 and 3(associate files with python, create shortcuts for installed applications) are automatically checked. 

all of this is when I double clicked python 3.7.3 in downloads

when I double click python 3.7.4 (I must have tried multiple times to install) in downloads I get an upgrade to python 3.7.4 with options "upgrade now" and "customization installation" both of which immediately lock me out and ask for administrative permission. 

For all I know as soon as I click the check boxes in 3.7.3 and click go it'll also freeze up and ask for administrative permissions. haha.

**Comment by yawpitch** [comment]
You can disable "for all users" and "python test suite" ... turning off the first should install (no admin permissions required) to your user account. You _do_ want "add python to environment variables" selected. You do not need "download debugging symbols" or "download debug binaries", but I believe those should be disabled if you've de-selected "python test suite", which is used to test the Python installation itself.

**Comment by VitruviusX** [comment]
"modify was successful"
"Thank you for using python 3.7.3 (32-bit)"

Am I all the way back at the beginning now haha.

**Comment by yawpitch** [comment]
If it's installed correctly you should now be able to open CMD.exe and type `python` and hit enter and get a Python interpreter session. You can then type `exit()` and hit enter and drop back to the shell.

If that _does not_ work I'm afraid you're going to have to have IT install this for you, because you're in a more-than-usually locked down Windows environment.

**Comment by VitruviusX** [comment]
Thank you, I typed python and it brought up what you said and I hit exit and it went back out to the regular command prompt. Am I anywhere near the ability to solve and submit the exercises on exercism? run the tests? I must be somewhat closer if I have the command prompt recognizing python right?

**Comment by VitruviusX** [comment]
OMG I typed pip3 install pytest and it went crazy and collected and downloaded and I think it worked.  I think I have pytest. Pytest version returns "version 5.0.1, imported fromm ..."

**Comment by VitruviusX** [comment]
I have python, CLI, PIP, and pytest.

**Comment by VitruviusX** [comment]
installed pytest-cache successfully. borderline tears in my eyes.

**Comment by yawpitch** [comment]
Excellent, that’s what I was hoping would happen. You should now be able to download exercises using the exercism CLI. You’ll then have to CD to the directory that it prints out and you can run `pytest` to run the test. They’ll all fail, but that’s a good thing. You can then edit the [EXERCISE].py file and then save and run `pytest` again, and repeat u til your code does not fail. Then you use the exercism CLI to submit using `exercism submit path/to/the/[EXERCISE].py`.

So you should be up and running with the basic tools.

Of course I now want to have a stern conversation with your IT team about basic proxy security, but I find myself wanting to have that conversation with about 90% of corporate IT departments, so we’ll pass on that for now. ;-)

**Comment by VitruviusX** [comment]
So I got the first exercise downloaded to the CLI after I configured the CLI. What do you mean by cd to the directory? Do I do all my work in this command prompt window or can I use a page I can edit on?

**Comment by VitruviusX** [comment]
Curious, do you think the proxy security is too high or too low for a hospital computer?

**Comment by yawpitch** [comment]
> So I got the first exercise downloaded to the CLI after I configured the CLI. What do you mean by cd to the directory? Do I do all my work in this command prompt window or can I use a page I can edit on?

Workflow is somewhat up to you. On Windows I'd say the simplest approach would be something like:

1. use the CLI to download an exercise; it will print out a path to where that exercise was downloaded. Highlight and copy that path (ie CTRL + C).
2. use the `cd` command to **c**hange **d**irectory to that path, ie `cd [CTRL + V to paste the path]`.
3. now you're in the working directory of the exercise; use `pytest` to run the tests, they'll fail.
4. in a separate Explorer file browser window browse to the same directory, you'll find a file called `[EXERCISE].py` (ie `hello_world.py`). Open this in your favorite text editor (ie Notepad++, Atom, Visual Studio: Code ... it doesn't really matter at this point, but it need to use plain text by default, NOT "rich text format" like the basic Notepad.exe tends to). You _may_ need to right click and use "Open in" rather than just double click, as the installer may have set things up so that double clicking will just run the file, _not_ open it for editing.
5. Edit the file, and when you're ready Save the file (ie CTRL + S).
6. Back in the CMD.exe window run `pytest` again.

From this point you edit in the text editor and you test in the console until the `pytest` command doesn't show any failures. Once it's working you can `exercism submit /path/to/[EXERCISE].py` to submit your work.

Unfortunately I have to tell you all this from memory, as I stopped using Windows years ago.

This IDLE editor included with Python can also be used to edit the file, however last I used it (about a decade ago) it did not have any way of running `pytest` directly. That may have changed, but you'll find that _a lot_ of coding is having a text editor and a console open and doing something similar to what I've described above over and over.

As for the network security; were it me you wouldn't be able to install using `pip` without doing so through a dedicated proxy server, or better yet a local mirror that the IT team used to only allow you access to modules they'd whitelisted. But then if it were me you wouldn't be able to connect to the Internet from your physical machine either.

**Comment by VitruviusX** [comment]
Thanks, everything seems to be in order. I have my command prompt window open and it is( --\exercism\python\hello-world) which means its accessing what im editing and saving from that folder of the same name? I've then played around with returning hello world, saving/running andd saving, and then  type pytest into the command prompt. 

I then get attribute errors. should I be doing somethin with the hello_world_test.py rather than hello_world.py?

I've done both:
def func():
             return "hello, world!"
def func():
             print("hello, world!")

with and without capital letters and both gave me this:


                    HelloWorldTest.test_hello _

self = <hello_world_test.HelloWorldTest testMethod=test_hello>

    def test_hello(self):
>       self.assertEqual(hello_world.hello(), 'Hello, World!')
E       AttributeError: module 'hello_world' has no attribute 'hello'

hello_world_test.py:10: AttributeError
1 failed in 0.06 seconds

Thank you again to everyones help, I feel like I'm miles closer since I'm running a test on the code I believe, although I get the same response if I save a blank page and run it...

**Comment by cmccandless** [comment]
> `def func()`

I think you might be getting your syntax mixed up. `def` is the keyword the indicates a function, the bit before the parenthesis is the function name. So when you get `AttributeError: module 'hello_world' has no attribute 'hello'`, that is saying that `hello_world.py` has no function, class, or variable named `hello`.

> I've done both:
def func():
return "hello, world!"
def func():
print("hello, world!")

The first one is closer to what you want.

**Comment by VitruviusX** [comment]
It passed. I was not using the correct function name like you said. Thank you for your help. I am no longer #Totally lost. Awesome community.

**Comment by cmccandless** [comment]
Glad to help. If your issue is resolved, please close this issue.
