### ISSUE TITLE
Requesting Feedback for Rust Core Exercise

### ISSUE THREAD

**Issue by n14little** [exercism/support#5]
Hi,

I would like feedback on one of the core exercises so that I can move on.

https://exercism.io/my/solutions/ec9ba2d95ece43f4b1fe89052907959f

**Comment by sshine** [comment]
Hi @n14little. The Rust track has been notoriously overwhelmed by student, and waiting times have been sky-high. I hope that you eventually got feedback on your core exercise or found your way to independent mode where there's no waiting time. I'm closing this issue as there's not much we can do in the short run. We are working on several measures to lower the waiting time for all tracks.
