### ISSUE TITLE
Workspace folder not visible

### ISSUE THREAD

**Issue by QQ-88** [exercism/support#50]
Hi everyone,

I installed exercism as per instructions (I believe) but cant find the workspace folder in my file manager.
When running `exercism debug` I get 'Workspace: /home/name/exercism' but when I maneuver there I do not see any such folder (also not hidden ones).

How can I resolve this?

**Comment by NobbZ** [comment]
The workspace folder will be created lazily only on your first download.

So to create it just use the `exercism download` command as shown on the exercises page.

**Comment by QQ-88** [comment]
Thanks, I somehow missed that step.
