### ISSUE TITLE
Tests not running on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by Bathant** [exercism/support#54]
Hi, 
I have tried to run tests for the Gigasecond problem 
but the terminal gives me this error: 

> This copy of libswiftCore.dylib requires an OS version prior to 10.14.4.
> Exited with signal code 6
> 
I'm working on Xcode 11.0 beta 3  & macOS 10.15 Beta version

**Comment by NobbZ** [comment]
Hello @Bathant!

Could you please tell us which track you are on?

**Comment by Bathant** [comment]
I'm on swift track

**Comment by NobbZ** [comment]
@exercism/swift could you take over?

**Comment by masters3d** [comment]
Catalina doesn’t support Xcode 10. You are going to need to upgrade to Xcode 11.

**Comment by Bathant** [comment]
@masters3d  sorry it was my mistake, i'm working on Xcode 11.0 beta 3

**Comment by masters3d** [comment]
Can you try deleting the Xcode file and recreate? Do you have Xcode 10 in your system? If so it may be the default. haven't upgraded ci yet to Catalina to test.

**Comment by Bathant** [comment]
@masters3d  Thank you, changing the default Xcode version solved my issue.
