### ISSUE TITLE
Need feedback on javascript track exercises

### ISSUE THREAD

**Issue by drio** [exercism/support#6]
Hello there. I was wondering if someone can take a look to my status. I am in the javascript track and I have 5 exercises for review (four of them are extra). It has been a while and I can't continue unless someone approves my submission. Thank you! 🙏

**Comment by kotp** [comment]
Closing this as it has received feedback.  I see it has now been over a week ago again, but appears to be waiting on student.  Let me know (you can reopen this issue if that is the case, as well).
