### ISSUE TITLE
Settup Catch2 in VS Code

### ISSUE THREAD

**Issue by CDEguia** [exercism/support#60]
I've been using the VS Code IDE to create my solutions for the C++ and would like to run the tests in the IDE, as opposed to on the CLI.

**Comment by sshine** [comment]
@CDEguia: You'll need to be a little more specific; e.g. is there something that the C++ track does that makes it impossible to run tests within the IDE? I notice that the C++ track uses Catch2. Do you think the track lacks instructions for getting an exercise's test suite executed within the IDE?

As you haven't responded in a while, I'm closing this issue. Feel free to get back.
