### ISSUE TITLE
Unable to submit the go solution 

### ISSUE THREAD

**Issue by raghunath** [exercism/support#64]
I am trying to upload the go exercise solution and keep getting the unable to submit metadata error. 

#command for submitting response.
```
exercism submit ../greeting.go hello_world.go hello_world_test.go README.md
Error: 
```

    The exercise you are submitting doesn't have the necessary metadata.
    Please see https://exercism.io/cli-v1-to-v2 for instructions on how to fix it.

any thoughts?

**Comment by raghunath** [comment]
Not sure for some reason not able to submit it. 

I have used the below command to change my workspace. 

`exercism configure -t xxxxx -w ~/go/src/exercism`

followed by downloaded the exercise. 
`# exercism download --exercise=hello-world --track=go`

Output:
```
Downloaded to
/home/user/go/src/exercism/go/hello-world
```
Now tried uploading from the '/home/user/go/src/exercism/go' folder. 

command used: 
```
~/go/src/exercism/go $ exercism submit greeting.go 
Error: 

    The exercise you are submitting doesn't have the necessary metadata.
    Please see https://exercism.io/cli-v1-to-v2 for instructions on how to fix it.
```

Also tried deleting and re-downloading for couple of time.

**Comment by raghunath** [comment]
$exercism troubleshoot

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.12
Latest:  3.0.12


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/user
Workspace: /home/user/go/src/exercism
Config:    /home/user/.config/exercism
API key:   xxxx*****************************xxx

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 1.020264798s

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 7.369707221s


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.

**Comment by NobbZ** [comment]
You need to `cd` into the exercise folder and submit from there.

Also having the `exercism` workspace in the `go` workspace (aka `GOPATH`) is not a good idea, as `exercism` might contain a lot of different languages.

**Comment by raghunath** [comment]
aah my bad! moving the file into exercise directory worked perfectly.  

Although Golang prompts with package error which is a different topic (`greeting.go:3:8: found packages main (greeting.go) and greeting (hello_world.go) in /home/user/go/src/exercism/go/hello-world`)

Thanks you very much for recommendations, will move the exercism away from GOPATH and issue can be closed.

**Comment by NobbZ** [comment]
> Although Golang prompts with package error which is a different topic (greeting.go:3:8: found packages main (greeting.go) and greeting (hello_world.go) in /home/user/go/src/exercism/go/hello-world)

The exercises are given in a way that there is no need to provide a `main` package for your solution.
