### ISSUE TITLE
JavaScript track: npm ERR! Maximum call stack size exceeded

### ISSUE THREAD

**Issue by clockelliptic** [exercism/support#65]
I am using WSL on Windows 10.

Suddenly I've been getting the following error upon running `npm install`:

```
npm WARN request-promise-core@1.1.2 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN request-promise-native@1.0.7 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /redacted/path/.npm/_logs/2019-09-24T06_50_00_707Z-debug.log

```

So I ran `npm install --save request@^2.34`

Then I ran `npm install` again and received a similar error:

```
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/torchl/.npm/_logs/2019-09-24T08_49_53_455Z-debug.log

```

This has been happening since I tried `npm install` on the `queen-attack` exercise. It occurs for all of the problems now.

**Comment by tejasbubane** [comment]
@clockelliptic Answers on stackoverflow suggest removing npm cache. Did you try that? 
`npm cache clean --force`

Ref: https://stackoverflow.com/questions/40566348/maximum-call-stack-size-exceeded-on-npm-install

**Comment by SleeplessByte** [comment]
And also remove node_modules in the directory and sibling directories you're trying to install in.

**Comment by clockelliptic** [comment]
@tejasbubane i tried `npm cache clean --force`, this does not solve the problem

@SleeplessByte i tried removing the node_modules in the directory and sibling directories to no avail

**Comment by clockelliptic** [comment]
Okay I seem to have solved the problem for myself.

1. I deleted all node_modules folders in all of my javascript exercise directories.
2. I ran `npm clean-install` in each directory
3. In some folders `npm clean-install` warned me that my package.json and package-lock.json were not in sync, and that I needed to run `npm install`
4. now, running `npm install` works

**Comment by SleeplessByte** [comment]
I think somewhere, somehow, one of the `node_modules` became corrupt, but somehow also something "global". I'm glad you solved it!

**Comment by datengx** [comment]
This problem still happened to me on exercise "protein-translation". I'm running WSL Ubuntu 16.04. I installed exercism from source.

npm version: 6.13.7
node version: v10.18.1

**Comment by SleeplessByte** [comment]
This problem is unrelated to Exercism.

**Comment by tejasbubane** [comment]
Hi @datengx can you try the following steps and let me know if it works?

1. On problem page, click `Update this exercise` and download your solution again. 

<img width="628" alt="Screenshot 2020-02-11 at 10 55 51 PM" src="https://user-images.githubusercontent.com/980783/74261957-05d08580-4d22-11ea-848a-d9408ad72850.png">

2. Then follow @clockelliptic's instructions from [above comment](https://github.com/exercism/support/issues/65#issuecomment-584743880).
