### ISSUE TITLE
 `require_relative': cannot load such file 

### ISSUE THREAD

**Issue by Rhodine** [exercism/support#68]
1.  **Issue**: Exercism exercise is not running  - Error message below
2. When i input the file path to run the test I received this in the command line:
$ ruby series_test.rb
series_test.rb:2:in `require_relative': cannot load such file -- C:/Users/rorle/Exercism/ruby/series/series (LoadError)
        from series_test.rb:2:in `<main>'

3. Troubleshooting Information
===========================

Version
----------------
Current: 3.0.12
Latest:  3.0.12

Operating System
----------------
OS:           windows
Architecture: amd64

Configuration
----------------
Home:      C:\Users\rorle
Workspace: C:\Users\rorle\Exercism
Config:    C:\Users\rorle\AppData\Roaming\exercism
API key:   2f4a*****************************e9d

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 112.17ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 119.3454ms

**Comment by NobbZ** [comment]
@sshine back when I asked, I was not in the team (or at least didn't know ;) ), also at that point in time, we hadn't write access to the CLI repository and therefore wouldn't have been able to move it at all.

The transfer button though should be to the right, righ tbelow the participants list and the "Lock conversation" and "Pin issue" "buttons".

**Comment by sshine** [comment]
@NobbZ: Thanks. :) I also asked Jeremy who told me.
