### ISSUE TITLE
Unbound Identifier in all test.scm files

### ISSUE THREAD

**Issue by tylerlaprade** [exercism/support#74]
![image](https://user-images.githubusercontent.com/5475199/66278653-35a1e500-e879-11e9-9dfb-9e919068dcf0.png)
I am using Chez Scheme, DrRacket (if anybody has better suggestions on Windows 10, please let me know). I can't run any of the tests locally because they all fail with the pictured error. What am I doing wrong?

**Comment by tylerlaprade** [comment]
My understanding is make chez is only for *NIX/Mac, but I'm running Windows. I'm trying to run the test file from within my IDE (Dr. Racket, although I'm open to any recommendations for better ones)

**Comment by NobbZ** [comment]
I didn't even know that DrRacket were able to do regular Scheme, I always thought its Racket only…

Also I have taken a look into the `Makefile`, I initially thought it were doiung some magic to set include pathes or similar, but its not.

So does `chez --script test.scm hello-world.scm` on a terminal in the exercises folder work or do you see an error then?

**Comment by tylerlaprade** [comment]
No, it doesn't recognize the command 'chez'. I'm beginning to suspect I failed to install Scheme properly 😔. How might I verify this?

**Comment by NobbZ** [comment]
Sorry, I have no clue about the installation process of `chez` or `guile` on windows.

Though usually I'd assume, that it sets up `PATH` correctly for you when you use the windows installer.

So check if the location you installed `chez` into is part of your `PATH` and add it if its not currently in there.

**Comment by tylerlaprade** [comment]
Hi, I got it working by running directly from command line. The command isn't "chez", it's just "scheme". I also had to add the folder with scheme.exe to my PATH
