### ISSUE TITLE
RuntimeException: '-BeExactly' is not a valid Should operator.

### ISSUE THREAD

**Issue by dummy4200** [exercism/support#77]
Fairly new to exercism I do not know what to do when I get this error message:

Trying to run the test suite for 'Get-SumOfMultiples" I get this message
>>RuntimeException: '-BeExactly' is not a valid Should operator.<<
What is the issue here?

```plain
Troubleshoot information
=================
PS C:\Users\bridg\Exercism> exercism troubleshoot

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.12
Latest:  3.0.12


Operating System
----------------
OS:           windows
Architecture: amd64


Configuration
----------------
Home:      C:\Users\bridg
Workspace: C:\Users\bridg\Exercism
Config:    C:\Users\bridg\AppData\Roaming\exercism
API key:   ae45*****************************63d

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 133.3763ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 231.598ms
```

**Comment by pwilson802** [comment]
I ran into the same issue, for anyone searching:

The tests use the Pester module, the syntax was changed in version 4 and you most likely have version 3.  Update to the latest version: 

`Install-Module -Name Pester -Force`

Restart the PowerShell window
