### ISSUE TITLE
Regarding "exercism fetch"

### ISSUE THREAD

**Issue by Anjali-R21** [exercism/support#8]
I came across here in around 2016 and I started with the Go
track on Linux and Windows but dropped it later.

Now I want to start another language track. I installed the CLI command line on Windows. But I am a bit lost.

Can anyone help me to do the following:
1) how do I change the working directory/ workspace
2) How do I call "exercism fetch" to start the new exercise? I am
pretty sure I used that command earlier, but I don't see it anymore in
the help menu.
3) How do I switch between language tracks?
I want to do these operation through the CLI, not online

**Comment by iHiD** [comment]
Can this be closed?

**Comment by Anjali-R21** [comment]
Yes its working now. Thanks
