### ISSUE TITLE
npm test errors

### ISSUE THREAD

**Issue by chantelledmello** [exercism/support#84]
Hi there, I'm attempting to run the npm test on my first JS exercise - Hello world - but keep getting this error. I downloaded the file via the command line as per the directions on the page, updated the subsequent hello-world.js file with my code and ran the ```$ npm test``` command. This are the error messages that I'm getting: 
<img width="1102" alt="Screen Shot 2019-11-11 at 7 35 55 PM" src="https://user-images.githubusercontent.com/26146422/68629578-be382480-04ba-11ea-963a-94b93c99a91c.png">

**Comment by NobbZ** [comment]
Hello @chantelledmello, it seems as if you were trying to run the tests from your users home directory, please use `cd` to navigate to the folder where the exercise was downloaded to and run the command again. Also please make sure you have installed the prerequisites first or do a `npm install` for each exercise after downloading in the exercises folder before running the tests the first time.

**Comment by SleeplessByte** [comment]
This should now be easier with the Web UI / editor. Let us know if you still have issues!
