### ISSUE TITLE
Problem with my account, please reply to my e-mail

### ISSUE THREAD

**Issue by luckylittle** [exercism/support#89]
I have sent an e-mail from `l***y@s****r.**` on `Fri Jan 31 03:01 UTC 2020` to `hello@exercism.io` about the issue i have with my account. I've got an automatic reply saying i also have to create an issue here.

**Comment by NobbZ** [comment]
@iHiD Could you please take over?

**Comment by iHiD** [comment]
If you signed up on the old website, then you would have signed up using GitHub. You need to log in using GitHub now.

**Comment by luckylittle** [comment]
That works, thanks.
