### ISSUE TITLE
I can't download exercises

### ISSUE THREAD

**Issue by paulcrouch99** [exercism/support#9]
1. -bash: exercism: command not found
2. I recently moved to MacOS from Windows and am trying to figure out how to use exercism and gradle on it. I did the "installing Java" part, but when I want to download an exercise, it tells me the message above. What am I doing wrong?

**Comment by iHiD** [comment]
Can this be closed?

**Comment by sshine** [comment]
I'm closing this issue as no response was given from @paulcrouch99.

Feel free to respond and it can be reopened.
