### ISSUE TITLE
Python Track

### ISSUE THREAD

**Issue by Muj18** [exercism/support#90]
Hi
I am new to GitHub and I am also new to Python.  i have signed up to the Python track and I just wanted to know how much Python knowledge will I have once I have completed the Python track? Enough to be comfortable in a job ?

**Comment by NobbZ** [comment]
That totally depends on what prior programming language you already have.

If you have enough knowledge in a language to feel comfortable in a job right now, then you'll probably feel comfident enough in python after a couple of exercises.

If though there is no prior knowledge in any programming language, then we can not answer the question for you. It depends to much on to many factors which we can not fully control, as your learning style, mentors availability or queue length.

Also I have to admit that the current design of exercism is not targetting students that start from scratch, its meant for those who already know a language and either want to broaden their reportoire or deepen knowledge in their main language.

Though it can work also from scratch for students that really hang into it and do not fear to do a loot of research on their own, as there is currently not much of language specific help in any exercise.
